name: Update Image CLI

on:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to ECR
        id: ecr
        uses: jwalton/gh-ecr-login@v3
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1

  build-and-push:
    runs-on: self-hosted
    needs: login
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Pablo-man/MicServiceUploadImages
          path: MicServiceUploadImages/CLI
      - uses: actions/checkout@v2
      - uses: vitr/actions-build-and-upload-to-ecs@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: micservice/uploadimages/cli
          region: us-east-2
          tags: latest,${{ github.sha }}
          create_repo: true