name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to ECR
        id: ecr
        uses: jwalton/gh-ecr-login@v3
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1

  build-and-push:
    runs-on: self-hosted
    needs: login
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Pablo-man/MicServiceUploadImages
          path: MicServiceUploadImages  
      - name: Build and Push CLI Microservice
        run: |
            docker build -t micservicecli . \
            && docker tag micservicecli:latest public.ecr.aws/s7f4a6o3/micservice/uploadimages/cli:latest \
            && docker push public.ecr.aws/s7f4a6o3/micservice/uploadimages/cli:latest
        working-directory: MicServiceUploadImages/CLI
        
  stop-and-remove:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop and remove existing containers
        run: |
          if docker ps -a | grep -q 'cli'; then
              docker stop cli
              docker rm cli
          fi
          if docker ps -a | grep -q 'list'; then
              docker stop list
              docker rm list
          fi
          if docker ps -a | grep -q 'upload'; then
              docker stop upload
              docker rm upload
          fi

  deploy:
    runs-on: self-hosted
    needs: stop-and-remove
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Docker Network
        run: |
          docker network create mi-red || echo "Network mi-red already exists"

      - name: Deploy microservice1
        run: |
          docker pull public.ecr.aws/s7f4a6o3/micservice/uploadimages/cli:latest && \
          docker run -d --name cli --network mi-red -p 4000:4000 public.ecr.aws/s7f4a6o3/micservice/uploadimages/cli:latest

      - name: Deploy microservice2
        run: |
          docker pull public.ecr.aws/s7f4a6o3/micservice/uploadimages/list:latest && \
          docker run -d --name list --network mi-red -p 9000:9000 public.ecr.aws/s7f4a6o3/micservice/uploadimages/list:latest

      - name: Deploy microservice3
        run: |
          docker pull public.ecr.aws/s7f4a6o3/micservice/uploadimages/upload:latest && \
          docker run -d --name upload --network mi-red -p 5000:5000 public.ecr.aws/s7f4a6o3/micservice/uploadimages/upload:latest
