name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to ECR
        id: ecr
        uses: jwalton/gh-ecr-login@v3
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1

  stop-and-remove:
    runs-on: self-hosted
    needs: login
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop and remove existing containers
        run: |
          if docker ps -a | grep -q 'cli'; then
              docker stop cli
              docker rm cli
          fi
          if docker ps -a | grep -q 'list'; then
              docker stop list
              docker rm list
          fi
          if docker ps -a | grep -q 'upload'; then
              docker stop upload
              docker rm upload
          fi

  deploy:
    runs-on: self-hosted
    needs: stop-and-remove
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Docker Network
        run: |
          docker network create mi-red || echo "Network mi-red already exists"

      - name: Deploy microservice1
        run: |
          docker pull public.ecr.aws/s7f4a6o3/micservice/uploadimages/cli@sha256:075b1aa3ecec290eb32cb8f6c99f2aaca1f4c0a6910b54a3f9939750265ac9df && \
          docker run -d --name cli --network mi-red -p 4000:4000 public.ecr.aws/s7f4a6o3/micservice/uploadimages/cli@sha256:075b1aa3ecec290eb32cb8f6c99f2aaca1f4c0a6910b54a3f9939750265ac9df

      - name: Deploy microservice2
        run: |
          docker pull public.ecr.aws/s7f4a6o3/micservice/uploadimages/list@sha256:b02809a481a6a31c73340d5a2c100ccdc32ce39a06e875db6fe5f671f4dfe9d8 && \
          docker run -d --name list --network mi-red -p 9000:9000 public.ecr.aws/s7f4a6o3/micservice/uploadimages/list@sha256:b02809a481a6a31c73340d5a2c100ccdc32ce39a06e875db6fe5f671f4dfe9d8

      - name: Deploy microservice3
        run: |
          docker pull public.ecr.aws/s7f4a6o3/micservice/uploadimages/upload@sha256:630546a86990e62532690788326ade4471179bcec57b7b8102468201ca999ad7 && \
          docker run -d --name upload --network mi-red -p 5000:5000 public.ecr.aws/s7f4a6o3/micservice/uploadimages/upload@sha256:630546a86990e62532690788326ade4471179bcec57b7b8102468201ca999ad7
