name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy microservice1
      run: |
        sudo su

    - name: 'Get Login to AWS ECR'
      id: ecr-login
      uses: thalesvon/ecr-login@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_OUTPUT: json
        AWS_REGION: us-east-1
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: 'get-login --no-include-email --region ${AWS_REGION}'
    - name: 'Docker Login'
      run: ${{ steps. ecr-login.outputs.login-string }}

    - name: Deploy microservice1
      run: |
        docker pull public.ecr.aws/s7f4a6o3/micservice/uploadimages/cli:latest && docker run --name cli -p 4000:4000 push public.ecr.aws/s7f4a6o3/micservice/uploadimages/cli:latest

    - name: Deploy microservice2
      run: |
        docker public.ecr.aws/s7f4a6o3/micservice/uploadimages/list:latest && docker run --name list -p 9000:9000 public.ecr.aws/s7f4a6o3/micservice/uploadimages/list:latest
    
    - name: Deploy microservice3
      run: |
        docker pull public.ecr.aws/s7f4a6o3/micservice/uploadimages/upload:latest && docker run --name upload -p 5000:5000 public.ecr.aws/s7f4a6o3/micservice/uploadimages/upload:latest
